export const SET_UP_MAIN_CONTENT = 'SET_UP_MAIN_CONTENT';

export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';
export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';
export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_TOP_RATED = 'FETCH_TOP_RATED';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_INIT = 'SEARCH_MOVIES_INIT';

export const AUTH_USER_BEGIN = 'AUTH_USER_BEGIN';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const AUTH_USER_INIT = 'AUTH_USER_INIT';

export const ADD_MOVIE_START = 'ADD_MOVIE_START';
export const ADD_MOVIE_SUCCESSS = 'ADD_MOVIE_SUCCESSS';
export const ADD_MOVIE_FAIL = 'ADD_MOVIE_FAIL';

export const FETCH_FAV_MOVIES_START = 'FETCH_FAV_MOVIES_START';
export const FETCH_FAV_MOVIES_SUCCESS = 'FETCH_FAV_MOVIES_SUCCESS';
export const FETCH_FAV_MOVIES_FAIL = 'FETCH_FAV_MOVIES_FAIL';

export const  UPDATE_MOVIES_SUCCESS = 'UPDATE_MOVIES_SUCCESS';
export const UPDATE_NOW_PLAYING = 'UPDATE_NOW_PLAYING';
export const UPDATE_POPULAR = 'UPDATE_POPULAR';
export const UPDATE_TOP_RATED = 'UPDATE_TOP_RATED';

export const UPDATE_MOVIES = 'UPDATE_MOVIES';
